service: go-dynamodb

frameworkVersion: "3"

custom:
  this: ${self:service}-${self:provider.stage}
  tableName: ${self:custom.this}-db

provider:
  name: aws
  architecture: arm64
  runtime: provided.al2
  stage: "poc"
  region: sa-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "*"
  
  environment:
    TABLE_NAME: ${self:custom.tableName}

package:
  individually: true

functions:
  main:
    handler: bootstrap
    package:
      artifact: bin/main.zip
    events:
      - http:
          path: /
          method: get
          cors: true

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
